### ISSUE TITLE
beat fails without admin or editor groups

### ISSUE THREAD

**Issue by josephlewis42** [GoogleCloudPlatform/pubsubbeat#13]
The beat fails with the error `Exiting: fail to create subscription: rpc error: code = PermissionDenied desc = User not authorized to perform this action.` if it doesn't have the ability to create a subscription on the account, even if the subscription already exists.

As a user I expect to have the ability to configure the beat with a minimal set of permissions--ideally just subscribe--for security purposes and not have it create resources on my account.

**Comment by Conky5** [comment]
I believe this is closed by https://github.com/GoogleCloudPlatform/pubsubbeat/pull/15.

**Comment by josephlewis42** [comment]
I believe you're right!
