### ISSUE TITLE
Create 1.2.0 release

### ISSUE THREAD

**Issue by Plantain** [GoogleCloudPlatform/pubsubbeat#20]
#17 is a significant usability improvement, please do an official release?

**Comment by ScubaDrew** [comment]
Is this project abandoned? It really works pretty well for my use-case but worried about the lack of attention. Are you using it still @Plantain ?

**Comment by SuperQ** [comment]
We still use it, but development is a bit slow. I have some things to work on, our holiday freeze is a godo time for this work. :smile:

**Comment by SuperQ** [comment]
Ping @josephlewis42, with the couple of merged features and switch to Go modules, would it be good to cut a release?

**Comment by josephlewis42** [comment]
You got it, done!

https://github.com/GoogleCloudPlatform/pubsubbeat/releases/tag/1.2.0

**Comment by SuperQ** [comment]
It looks like the new release changes the released binary layout. Maybe we should use a tool like goreleaser to create the packages.

**Comment by josephlewis42** [comment]
@SuperQ they should now match the old one (with the exception of Windows, which is now missing the .exe)

We were originally using the Elastic packagers for this repo, but incompatibilities started to crop up with Python, Docker daemons, and Travis.
