### ISSUE TITLE
Make command no longer produces ./pubsubbeat binary

### ISSUE THREAD

**Issue by dlmather** [GoogleCloudPlatform/pubsubbeat#32]
Running `make` on its own used to produce the pubsubbeat binary in the project directory. Now it can only be produced via `make build` which also changes the path to ./bin/. Happy to raise a PR on the README, but it was unclear to me if this was an intentional change.

**Comment by josephlewis42** [comment]
Better yet, I'll fix it for you! You should be good to go now.
